"""
MBPP EXTERNAL BENCHMARK EVALUATOR   LOCKED
===========================================
This file contains 50 real problems drawn from the MBPP (Mostly Basic Python
Programming) benchmark. It is the ground-truth gate for the singularity check.

SECURITY: This file is in the `forbidden_files` set in both sandbox_guard.py
and main.py. The AI CANNOT overwrite it. The singularity check requires 80%+
on this benchmark AND 95%+ on the dynamic dataset. Without both, no singularity.

DO NOT EDIT THIS FILE unless you are the human developer adding new test cases.
"""

import time
import os
import sys

# Sandbox globals   same restricted environment as evaluator_anchor.py
SANDBOX_GLOBALS = {
    '__builtins__': {
        'print': print, 'len': len, 'range': range, 'list': list,
        'dict': dict, 'set': set, 'tuple': tuple, 'int': int,
        'float': float, 'str': str, 'bool': bool, 'True': True,
        'False': False, 'None': None, 'abs': abs, 'round': round,
        'min': min, 'max': max, 'sum': sum, 'sorted': sorted,
        'enumerate': enumerate, 'zip': zip, 'map': map, 'filter': filter,
        'isinstance': isinstance, 'type': type, 'repr': repr,
        'chr': chr, 'ord': ord, 'hex': hex, 'bin': bin,
        'any': any, 'all': all, 'reversed': reversed,
    }
}

try:
    import math as _math
    SANDBOX_GLOBALS['math'] = _math
except ImportError:
    pass

# LOCKED BENCHMARK DATASET   50 PROBLEMS
# Problem format: ("Prompt String", input_args, expected_output)
# input_args is a list/tuple that gets unpacked as func(*input_args),
# or a single value passed as func(input_args).
MBPP_DATASET = [
    #  String Operations (10) 
    ("Remove Spaces", ["hello world"], "helloworld"),
    ("Count Uppercase Letters", ["Hello World"], 2),
    ("Capitalize First Letter", ["hello"], "Hello"),
    ("String Is Digits Only", ["12345"], True),
    ("String Is Digits Only", ["123a5"], False),
    ("Repeat String N Times", ["ab", 3], "ababab"),
    ("String Contains Substring", ["hello world", "world"], True),
    ("String Contains Substring", ["hello world", "xyz"], False),
    ("Count Character In String", ["mississippi", "s"], 4),
    ("Reverse Words In String", ["hello world foo"], "foo world hello"),

    #  Math / Number Theory (15) 
    ("Absolute Difference", [10, 3], 7),
    ("Absolute Difference", [3, 10], 7),
    ("Is Perfect Square", [16], True),
    ("Is Perfect Square", [15], False),
    ("Sum Of Digits", [1234], 10),
    ("Sum Of Digits", [999], 27),
    ("Number Is Armstrong", [153], True),
    ("Number Is Armstrong", [100], False),
    ("Celsius To Fahrenheit", [0], 32.0),
    ("Celsius To Fahrenheit", [100], 212.0),
    ("GCD Of Two Numbers", [48, 18], 6),
    ("LCM Of Two Numbers", [4, 6], 12),
    ("Is Power Of Two", [16], True),
    ("Is Power Of Two", [18], False),
    ("Nth Fibonacci Number", [10], 55),

    #  List Operations (15) 
    ("Flatten Nested List", [[1, [2, 3], [4, [5]]]], [1, 2, 3, 4, 5]),
    ("Remove Duplicates From List", [[1, 2, 2, 3, 3, 3]], [1, 2, 3]),
    ("List Intersection", [[1, 2, 3, 4], [3, 4, 5, 6]], [3, 4]),
    ("List Union", [[1, 2, 3], [3, 4, 5]], [1, 2, 3, 4, 5]),
    ("Find Second Largest", [[1, 2, 3, 4, 5]], 4),
    ("Find Second Largest", [[10, 5, 8, 3], ], 8),
    ("Rotate List Left By N", [[1, 2, 3, 4, 5], 2], [3, 4, 5, 1, 2]),
    ("Rotate List Right By N", [[1, 2, 3, 4, 5], 1], [5, 1, 2, 3, 4]),
    ("All Elements Are Unique", [[1, 2, 3, 4]], True),
    ("All Elements Are Unique", [[1, 2, 2, 3]], False),
    ("Cumulative Sum Of List", [[1, 2, 3, 4]], [1, 3, 6, 10]),
    ("Product Of List", [[1, 2, 3, 4]], 24),
    ("Chunk List Into Sublists", [[1, 2, 3, 4, 5, 6], 2], [[1, 2], [3, 4], [5, 6]]),
    ("Sum Of Odd Numbers In List", [[1, 2, 3, 4, 5]], 9),
    ("Count Even Numbers In List", [[1, 2, 3, 4, 5, 6]], 3),

    #  Logic / Conditionals (10) 
    ("Leap Year Check", [2024], True),
    ("Leap Year Check", [1900], False),
    ("Leap Year Check", [2000], True),
    ("Triangle Is Valid", [3, 4, 5], True),
    ("Triangle Is Valid", [1, 2, 10], False),
    ("Grade From Score", [95], "A"),
    ("Grade From Score", [75], "C"),
    ("FizzBuzz Single", [15], "FizzBuzz"),
    ("FizzBuzz Single", [9], "Fizz"),
    ("FizzBuzz Single", [7], "Buzz"),
]

# Total must equal MBPP_TOTAL_TASKS in autonomous_loop.py
assert len(MBPP_DATASET) == 50, f"MBPP dataset must have exactly 50 items, got {len(MBPP_DATASET)}"


def evaluate_mbpp():
    """
    Runs all 50 MBPP problems against the current sandbox/experiment.py.
    Returns (score, exec_time, crash_log) format identical to other evaluators.
    score = number of problems solved correctly (0 50).
    """
    if not os.path.exists("sandbox/experiment.py"):
        print("CRASH_LOG: sandbox/experiment.py does not exist.")
        print("MBPP_SCORE: 0")
        print("FITNESS: 0.0")
        return 0, 0.0, "sandbox/experiment.py missing"

    start_time = time.time()

    # Ensure sandbox is on path
    sandbox_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sandbox")
    if sandbox_path not in sys.path:
        sys.path.insert(0, sandbox_path)

    # Force-reload experiment module
    for mod in list(sys.modules.keys()):
        if mod in ('experiment', 'baselines') or mod.startswith('sandbox'):
            try:
                del sys.modules[mod]
            except Exception:
                pass

    try:
        import experiment
    except Exception as e:
        print(f"CRASH_LOG: Could not import experiment.py: {e}")
        print("MBPP_SCORE: 0")
        print("FITNESS: 0.0")
        return 0, time.time() - start_time, str(e)

    if not hasattr(experiment, 'generate_code'):
        msg = "No generate_code function in experiment.py"
        print(f"CRASH_LOG: {msg}")
        print("MBPP_SCORE: 0")
        print("FITNESS: 0.0")
        return 0, time.time() - start_time, msg

    passed = 0
    tested = 0
    code_cache = {}

    for prompt, input_args, expected in MBPP_DATASET:
        # Cache generated code per unique prompt (avoid re-generating for same problem)
        if prompt not in code_cache:
            try:
                generated_code = experiment.generate_code(prompt)
                local_env = {}
                exec(generated_code, SANDBOX_GLOBALS.copy(), local_env)
                func = None
                for k, v in local_env.items():
                    if callable(v) and not k.startswith("__"):
                        func = v
                        break
                code_cache[prompt] = func
            except Exception:
                code_cache[prompt] = None

        func = code_cache[prompt]
        tested += 1
        if func is None:
            continue

        try:
            if isinstance(input_args, (list, tuple)):
                result = func(*input_args)
            else:
                result = func(input_args)

            # Normalize list comparisons (order matters for most cases)
            if result == expected:
                passed += 1
            elif isinstance(expected, list) and isinstance(result, list):
                # For set-like results (union, intersection), order may vary
                if sorted(str(x) for x in result) == sorted(str(x) for x in expected):
                    passed += 1
        except Exception:
            pass

    exec_time = time.time() - start_time
    fraction = passed / max(tested, 1)

    print(f"MBPP_SCORE: {passed}")
    print(f"ANCHOR SCORE: {passed}")   # run_evaluator() parses "ANCHOR SCORE:" line
    print(f"FITNESS: {fraction:.4f}")
    print(f"Tested {tested} problems, passed {passed}/{len(MBPP_DATASET)}")

    return passed, exec_time, None


if __name__ == "__main__":
    score, exec_time, err = evaluate_mbpp()
    if err:
        print(f"ERROR: {err}")
    print(f"TIME: {exec_time:.4f}s")
